/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#c2652a",
        "primary-container": "#e08850",
        "primary-fixed": "#fbe8d8",
        "primary-fixed-dim": "#f0a878",
        "on-primary": "#ffffff",
        "on-primary-container": "#fbe8d8",
        "surface": "#faf5ee",
        "surface-bright": "#faf5ee",
        "surface-dim": "#dcd6cc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f0e8",
        "surface-container": "#f2ece4",
        "surface-container-high": "#ece6dc",
        "surface-container-highest": "#e6e0d6",
        "background": "#faf5ee",
        "on-surface": "#3a302a",
        "on-surface-variant": "#605850",
        "on-background": "#3a302a",
        "outline": "#9a9088",
        "outline-variant": "#d8d0c8",
        "tertiary": "#8c3c3c",
        "tertiary-container": "#d47070",
        "secondary": "#78706a",
        "secondary-container": "#eae2da",
        "error": "#c0392b",
        "error-container": "#fce4e0",
      },
      fontFamily: {
        headline: ["EB Garamond", "serif"],
        display: ["EB Garamond", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "SFMono-Regular", "monospace"],
      },
      boxShadow: {
        soft: "0 2px 16px rgba(58, 48, 42, 0.04)",
        card: "0 4px 20px -2px rgba(58, 48, 42, 0.06)",
      },
    },
  },
  plugins: [],
};
